apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- configmap.yaml
- postgresql.yaml

namespace: dev
nameSuffix: -dev

commonLabels:
  environment: dev

images:
- name: sample-backend # match images with this name
  newName: aws-test-account.dkr.ecr.us-west-2.amazonaws.com/sample-backend # override the name
  newTag: dev # override the tag
