apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-setup
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:11.5
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-db-setup