apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-backend
    environment: stable
  name: sample-backend-stable-elb
  namespace: stable
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: backend
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: sample-backend
    environment: stable
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-dashboard
    environment: stable
  name: sample-dashboard-stable-elb
  namespace: stable
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: dashboard
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: sample-dashboard
    environment: stable
