apiVersion: v1
kind: Pod
metadata:
  name: pgadmin4
spec:
  containers:
  - name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - name: server
        containerPort: 80
        protocol: TCP
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: none@gmail.com
      - name: PGADMIN_DEFAULT_PASSWORD
        value: aVsmu0IW#01tg