name: branch-pr

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Grant git permission
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: fmt
      run: go fmt ./...
      
    - name: vendor
      run: go mod download

    - name: go build
      run: go build -i -o backend-sample

    - name: go test
      run: go test -cover -race -v ./...
