apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- rbac.yaml
- service.yaml
- statefulset.yaml
- configmap.yaml
- storage.yaml

commonLabels:
  app: hashicorp-vault
  environment: dev

configMapGenerator:
- name: vault-config-template
  files:
    - config.hcl.template
    - vault-csr.json.template

images:
  - name: hashicorp-vault # match images with this name
    newTag: unstable # override the tag
    newName: gcr.io/secret-store-devtest/hashicorp-vault # override the name