---
apiVersion: v1
kind: Service
metadata:
  name: hashicorp-vault-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: hashicorp-vault
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.1
  externalTrafficPolicy: Cluster
  selector:
    app: hashicorp-vault
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
      protocol: TCP
    - name: replicate
      port: 8201
      targetPort: 8201
      protocol: TCP