---
apiVersion: v1
kind: Service
metadata:
  name: sample-backend
spec:
  clusterIP: None
  ports:
    - name: backend
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: sample-backend
---
apiVersion: v1
kind: Service
metadata:
  name: sample-dashboard
spec:
  clusterIP: None
  ports:
    - name: dashboard
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: sample-dashboard